version: '3.8'
networks:
  mynetwork:

services:
  nproxy:
    container_name: nproxy
    image: nproxy
    build:
      context: ./nginx
    ports:
        - 80:80
    networks:
       - mynetwork

  time_service:
    container_name: time_service
    image: time_service
    networks:
       - mynetwork

